name: Lint and Format Check

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Run Prettier
        run: npm run format -- --check

      - name: Run ESLint
        run: npm run lint
